---

mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_db_pass: foobar
monitoring_db_pass: foobar

tmp_dir: '/tmp'

event_scheduler: 1

innodb_buffer_pool_size: 8M
innodb_log_file_size: 512M
innodb_log_buffer_size: 8M
innodb_log_files_in_group: 2
key_buffer_size: 8M
innodb_flush_log_at_trx_commit: 1
innodb_lock_wait_timeout: 20

tmp_table_size: 128M
max_heap_table_size: 128M

max_allowed_packet: 64M


mysql_data_dir: '/var/lib/mysql'
mysql_version: '5.6'
mysql_apt_config_ver: '0.7.3-1'